#!/bin/bash
# secd-to-c.sh — Convert .secd bytecode to C header
#
# Copyright (C) 2026
# License: GPL3
#
# Usage: ./secd-to-c.sh input.secd output.h

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 input.secd output.h"
    exit 1
fi

INPUT="$1"
OUTPUT="$2"

if [ ! -f "$INPUT" ]; then
    echo "Error: Input file not found: $INPUT"
    exit 1
fi

# Get filename for variable name
VARNAME=$(basename "$INPUT" .secd | tr '-' '_' | tr '.' '_')

# Generate C header
cat > "$OUTPUT" << EOF
/*
 * Auto-generated bytecode file
 * Source: $(basename "$INPUT")
 * Do not edit manually
 */

#ifndef BYTECODE_${VARNAME}_H
#define BYTECODE_${VARNAME}_H

#include <stdint.h>
#include <stddef.h>

static const uint8_t bytecode_${VARNAME}[] = {
EOF

# Convert binary to C array
xxd -i "$INPUT" | sed 's/unsigned char/    /' | sed 's/};/};/' >> "$OUTPUT"

cat >> "$OUTPUT" << EOF

};

static const size_t bytecode_${VARNAME}_size = sizeof(bytecode_${VARNAME});

#endif /* BYTECODE_${VARNAME}_H */
EOF

echo "Created: $OUTPUT"
echo "  Variable: bytecode_${VARNAME}"
echo "  Size: $(wc -c < "$INPUT") bytes"
