(defpackage :diag (:use :common-lisp :secd-lisp) (:export :main))
(in-package :diag)

(defun main ()
  (%usb-init)
  (%usb-hid-add)
  (%usb-mouse-add)
  (%usb-start)
  (let ((tick 0))
    (loop
      (let ((s (%hid-mouse 0 1 0 0)))
        (print tick)
        (print s))
      (%sleep 100)
      (setf tick (+ tick 1)))))