;;;;; main.lisp — Main entry point for secd-lisp
;;;;
;;;; Copyright (C) 2026
;;;; License: GPL3
;;;;
;;;; Command line interface (clingon) and main entry point for the compiler.

(in-package #:secd-lisp)

;;; Print usage
(defun print-usage (stream)
  "Print usage information."
  (format stream "secd-lisp - secd-lisp compiler for SECD machine~%")
  (format stream "~%")
  (format stream "Usage: secd-lisp [options] <source.lisp>~%")
  (format stream "~%")
  (format stream "Compiles a SECD-LISP SOURCE file into a .uf2 firmware image~%")
  (format stream "by merging the generated bytecode with the target's .machine~%")
  (format stream "firmware archive.~%")
  (format stream "~%")
  (format stream "Options:~%")
  (format stream "  -o, --output <file>    Output .uf2 file (default: <source>.uf2)~%")
  (format stream "  -t, --target <name>    Target (rp2040-zero, rp2350-beetle, ...)~%")
  (format stream "      --machine <dir>    Add a directory to search for .machine~%")
  (format stream "                         firmware archives (repeatable)~%")
  (format stream "      --lib <dir>        Add a library search path (repeatable)~%")
  (format stream "      --entry <pkg:fn>   Entry point function (default secd:main)~%")
  (format stream "  -h, --help             Show this help~%")
  (format stream "      --version          Show version~%")
  (format stream "~%Machine archives are searched in the .machine --machine dirs plus~%")
  (format stream "the default locations. Lisp libraries come from library/, --lib,~%")
  (format stream "and the SECD_LIB environment variable (colon-separated).~%"))

;;; The clingon command for the compiler CLI.
(defun make-secd-lisp-command ()
  (clingon:make-command
   :name "secd-lisp"
   :description "secd-lisp compiler for SECD machine."
   :version (asdf:component-version (asdf:find-system :secd-lisp))
   :options (list
             (clingon:make-option :string
                              :short-name #\o
                              :long-name "output"
                              :description "Output .uf2 file (default: <source>.uf2)."
                              :key :output-file)
             (clingon:make-option :string
                                  :short-name #\t
                                  :long-name "target"
                                  :description "Target platform (e.g. rp2040-zero)."
                                  :key :target)
             (clingon:make-option :list
                                  :long-name "machine"
                                  :description "Add a .machine search dir (repeatable)."
                                  :key :machine)
             (clingon:make-option :list
                                  :long-name "lib"
                                  :description "Add a library search path (repeatable)."
                                  :key :lib-paths)
             (clingon:make-option :string
                                  :long-name "entry"
                                  :description "Entry point function (default SECD:MAIN)."
                                  :key :entry)
             (clingon:make-option :flag
                                  :short-name #\h
                                  :description "Show this help."
                                  :key :help))
   :handler #'secd-lisp-handler))


(defun add-library-from-path (p)
  "add a library search path when non-blank."
  (let ((p (string-trim " " p)))
    (when (string/= p "")
      (add-library-search-path p))))

(defun add-environment-library-paths ()
  "Add SECD_LIB environment entries (colon/semicolon separated) to the
library search path."
  (let ((env (uiop:getenv "SECD_LIB")))
    (when (and env (string/= env ""))
      (dolist (dir (uiop:split-string env :separator '(#\; #\:)))
        (add-library-from-path dir)))))

;;; Prepend DIR to the .machine search paths so a user-supplied directory is
;;; searched before the built-in defaults.
(defun add-machine-search-path (dir)
  (let ((s (string-trim " " dir)))
    (when (string/= s "")
      (push s *machine-search-paths*))))


(defun secd-lisp-handler (cmd)
  (when (clingon:getopt cmd :help)
    (print-usage *standard-output*)
    (clingon:exit 0))
  (let ((input-file (first (clingon:command-arguments cmd))))
    (unless input-file
      (print-usage *error-output*)
      (clingon:exit 1))
    (let* ((target-name (intern (string-upcase (or (clingon:getopt cmd :target)
                                                   "RP2040"))
                                "KEYWORD"))
           (esp32-target (search "ESP32" (symbol-name target-name)))
           (output-file (or (clingon:getopt cmd :output-file)
                            (format nil "~A.~A"
                                    (pathname-name (pathname input-file))
                                    (if esp32-target "bin" "uf2"))))
           (entry-fn (or (clingon:getopt cmd :entry) "SECD:MAIN")))
      (handler-case
          (progn
            (dolist (dir (clingon:getopt cmd :machine))
              (add-machine-search-path dir))
            (dolist (dir (clingon:getopt cmd :lib-paths))
              (add-library-from-path dir))
            (add-environment-library-paths)
            (format t "Loading machine: ~A~%" target-name)
            (set-target target-name)
            (print-target-info)
            (format t "~%Compiling ~A to ~A~%" input-file output-file)
            (let ((bytecode (secd-compile-file input-file
                                               :target target-name
                                               :entry entry-fn)))
              (format t "Bytecode: ~A bytes~%" (length bytecode))
              (format t "Merging with firmware: ~A~%"
                      (target-firmware-path *target*))
              (link-machine (target-firmware-path *target*) bytecode output-file)
              (format t "Compiled successfully to ~A~%" output-file)
              (when esp32-target
                (format t "~%Flash (bootloader 0x1000, ptable 0x8000, app+bytecode 0x10000):~%")
                (format t "  esptool.py write_flash 0x1000 bootloader.bin 0x8000 partition-table.bin 0x10000 ~A~%"
                        output-file)
                (format t "Or re-link a newer program without touching the firmware:~%")
                (format t "  cat firmware.bin <name>.secd > final.bin~%"))))
        (error (e)
          (format t "Error: ~A~%" e)
          (clingon:exit 1)))))
  (clingon:exit 0))

;;; Main entry point
(defun main ()
  "Main entry point for secd-lisp compiler."
  (clingon:run (make-secd-lisp-command)))